repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-ast
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-toml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.1.13"
    hooks:
      - id: ruff
        args:
          [
            "--ignore=PT023,PLR2004,S104,FIX002,B024,TD002,TD003,EM,FBT,TRY003,S101,D1,FA,ANN101,PGH003",
            "--fixable=ALL",
            "--select=ALL",
            "--unsafe-fixes",
            "--exclude=migrations,test",
            "--fix",
          ]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.8.0"
    hooks:
      - id: mypy
        exclude: "tools/"
        args: ["--strict"]
