services:
  store-api-app:
    build:
      context: ./
      dockerfile: ./Dockerfile
      args:
        POETRY_DEP_GROUP: "main"
    command: python -m src
    volumes:
      # for application reload and save
      - ./src:/store_project/src
      # config
      - type: "bind"
        source: "./config"
        target: "/store_project/src/config"
        read_only: true
    environment:
      - CONFIG_PATH=/store_project/src/config/config.toml
    depends_on:
      dev-db:
        condition: service_healthy

  dev-db:
    image: postgres:latest
    restart: on-failure
    env_file:
      # Must be same vars as ./config/config.toml
      - .dev.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $$POSTGRES_DB -U $$POSTGRES_USER"]
      interval: 5s
      timeout: 20s
      retries: 5
    ports:
      - 5433:5432
    volumes:
      # save db data
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
