[api]
host = "0.0.0.0"
port = 8000
debug = true

[db]
host = "localhost"
port = 5432
database = "store_project"
user = "admin"
password = "admin"
echo = true

[logging]
level = "DEBUG"
path = "./logs/"
