[api]
host = "0.0.0.0"
port = 8000
debug = true

[db]
host = "localhost"
port = 5432
database = "store_project"
user = "giorno"
password = "giovanno"
echo = true

[logging]
level = "DEBUG"
render_json_logs = false
