[api]
host = "0.0.0.0"
port = 8000

[db]
host = "store_project.postgres"  # POSTGRES_HOST
port = 5432  # POSTGRES_PORT
database = "store_project"  # POSTGRES_DB
user = "admin"  # POSTGRES_USER
password = "admin"  # POSTGRES_PASSWORD
echo = true

[logging]
level = "DEBUG"
path = "./logs/"

[event_bus]
host = "store_project.rabbitmq"
port = 5672
login = "admin"
password = "admin"
