name: Lint

on:
  push:
    branches: ["main"]

jobs:
  starlette:
    runs-on: ubuntu-latest
    strategy:
      matrix:
          python-version: ['3.11']
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install mypy
        run: pip install mypy
      - name: Run mypy
        run: mypy . --strict

      - name: Install ruff
        run: pip install ruff
      - name: Run ruff
        run: ruff check . --ignore=I,EM,FBT,TRY003,S101,D1,FA,ANN101,PGH003 --fixable=ALL --select=ALL --unsafe-fixes --exclude migrations,tests